sonar.projectKey=NatanRigailo_mfa-app
sonar.organization=natanrigailo

sonar.sources=.
sonar.exclusions=static/**,templates/**,deploy/**

sonar.coverage.exclusions=**/*_test.go
sonar.cpd.exclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
