sonar.projectKey=NatanRigailo_mfa-app
sonar.organization=natanrigailo

sonar.sources=.
sonar.exclusions=venv/**,migrations/**,static/**,**/__pycache__/**

sonar.python.version=3.12

# Coverage reporting disabled until unit tests are implemented
sonar.coverage.exclusions=**/*
