apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mfa-app.fullname" . }}
  labels:
    {{- include "mfa-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.config.secretKey | quote }}
  EDIT_PASS: {{ .Values.config.editPass | quote }}
  API_TOKEN: {{ .Values.config.apiToken | quote }}
  {{- if .Values.config.dbPassword }}
  DB_PASSWORD: {{ .Values.config.dbPassword | quote }}
  {{- end }}
